name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run tests
        run: bash ./gradlew testDebugUnitTest

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: app/build/test-results/testDebugUnitTest/TEST-*.xml

      - name: Build Android app
        run: bash ./gradlew assembleDebug

      - name: Build wasmJs app
        run: bash ./gradlew wasmJsBrowserDistribution